// Generated by CoffeeScript 1.4.0
(function() {
  var CoffeeKiq, CoffeeKiqCron,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  CoffeeKiq = require('coffeekiq');

  CoffeeKiqCron = (function(_super) {

    __extends(CoffeeKiqCron, _super);

    function CoffeeKiqCron() {
      return CoffeeKiqCron.__super__.constructor.apply(this, arguments);
    }

    CoffeeKiqCron.prototype.find = function(name) {
      return this.redis_client.hgetall("cron_job:" + name);
    };

    return CoffeeKiqCron;

  })(CoffeeKiq);

  exports.CoffeeKiqCron = CoffeeKiqCron;

}).call(this);
